### ISSUE TITLE
problem with watch option

### ISSUE THREAD

**Issue by bmeyer71** [klen/python-scss#11]
It appears that when I use:

scss -w test.scss:test.css
or
scss -w test.scss

all it outputs in the css file is `<scss.parser.Stylesheet object at 0x1c3ca10>`

Did I miss something?

**Comment by klen** [comment]
Fixed in version 0.8.3

Thanks

**Comment by bmeyer71** [comment]
Excellent. Works great now. Thanks for the quick fix.
