### ISSUE TITLE
semi-colon being stripped

### ISSUE THREAD

**Issue by bmeyer71** [klen/python-scss#12]
Noticed that the semi-colon from the last line of a selector is being stripped out. I don't see that happening in SASS.

**Comment by klen** [comment]
Python-scss not have target to be copy of SASS. But I agree with you about last semi-colon. Now it stripped only when compress option enabled (@option compress: true, -m, --compress).

Fixed in version 0.8.3

**Comment by bmeyer71** [comment]
Thanks again for the quick fix.

Probably shouldn't have compared it to SASS. It was more of a visual thing.

I appreciate what you are doing with this project.
Thanks and keep up the Great work.
