### ISSUE TITLE
Pypi issue with version number

### ISSUE THREAD

**Issue by ncadou** [klen/python-scss#14]
Hi there, sometimes scss 0.8.4 isn't installed, an older version is (0.8.22 but I don't recall exactly).

I'm not really sure where the bug would be, but it seems to me that pypi thinks (arguably rightfully so) that 0.8.4 is older than 0.8.22.

I guess 0.8.22 should have been 0.8.2.2. Is there a 0.9 or higher release planned anytime soon? I believe that a quick release would put an end the versioning woes I'm going through right now.

**Comment by klen** [comment]
My error. Version 0.8.50 uploaded.

**Comment by ncadou** [comment]
Awesome, thanks!
