### ISSUE TITLE
Problems with @import

### ISSUE THREAD

**Issue by dramon** [klen/python-scss#18]
Situation:
Fedora 14, Python 2.7 in virtualenv:
Django==1.3.1
MySQL-python==1.2.3
Pygments==1.4
bpython==0.10.1
pyparsing==1.5.6
scss==0.8.60
wsgiref==0.1.2

File _common.scss:
@mixin id_barcode {
    font-size: 500%;
    text-transform: uppercase;
}

File: cloth.scss:
@import "common.scss";
# id_barcode_existing, #id_barcode_new {

```
@include id_barcode;
```

}

1st. problem:
Following @import instructions from http://sass-lang.com/docs/yardoc/file.SASS_REFERENCE.html#import don't lead to expecting behavioral but a message "@import "common"; Expected end of text (at char 38), (line:2, col:1)"

2nd. problem
Solution of 1. is delete @import line completely, because when I run "scss" with "-w" param it's working. And it's wrong IMHO.

3rd. problem:
"scss -w" convert all .SCSS files including them which begin with underscore. Result are empty files because this type of files is designed to include and contains usually only variables and mixins.

**Comment by klen** [comment]
"@import '...'" not support scss now. You can change "@import '...'" on "@import url("...");" and use zeta-library for compile static.

Or you may use pyscss, its more scss compatable: https://github.com/Kronuz/pyScss

Thanks for report.
