### ISSUE TITLE
Space inserted before pseudo-selector

### ISSUE THREAD

**Issue by wwight** [klen/python-scss#2]
I'm using scss 0.4.2.

calling `parser.parse('.foo:hover { color:#fff; }')`
returns: `'.foo :hover {\n\tcolor: #fff}'`

Parsing inserts a space between the `.foo` class and the `:hover` pseudo-class. Since `.foo:hover` and `.foo :hover` are logically different in CSS, this seems like a problem with the parser. Google hasn't yielded a good workaround for this problem, though using `&:hover` with nesting works in cases where nesting makes sense.

Keep up the good work!

**Comment by klen** [comment]
Fixed in version 0.4.4, thanks!

**Comment by wwight** [comment]
Works great, thanks a lot.
