### ISSUE TITLE
CSS3 transitions

### ISSUE THREAD

**Issue by mrIntegrator** [klen/python-scss#23]
Support for CSS3 transforms would be nice.

Currently "Unknown declaration" warnings are generated for:
- transition-property
- transition-duration
- transition-timing-function
- transition-delay
- transition
- all of the above with vendor prefixes (-moz-, -webkit-, -o-, -ms-)

Also a problem occurs during rendering:

{ transition-duration: 1s; } is rendered as { transition-duration: 1 s; } which causes the browser to ignore it due to the added space.

Same problem occurs when specify time values for 'transition-delay' and the shorthand 'transition'.

Possible values are 's' for seconds and 'ms' for milliseconds.

**Comment by klen** [comment]
Fixed in version 0.8.51.

Also you can use option: '-W' for disable warnings. Or @option warn:false in your source.
