### ISSUE TITLE
Watch mode doesn't process newly created .scss files

### ISSUE THREAD

**Issue by Jakobud** [klen/python-scss#30]
I'm not sure if this is the expected behavior or not, but lets say I am starting a new project.  There is a folder called `css`.  The folder is empty.  I have not created any scss or css files yet since it's a new project.

I want to use SCSS to watch that folder and process any scss files to css files as I work.

`scss -w /path/to/projects/css`

Now, when I create a new .scss file in that folder, I would expect SCSS to see this and to process it, creating a new .css file automatically.  But it doesn't do it.  Apparently, it seems that SCSS's watch mode only watches .scss files that existed at the moment that you ran `scss -w`.  It seems like it should be able to easily pick up newly created .scss files as well, but it doesn't.  So every time I add a new .scss file to my project, I have to restart the scss watch mode.

Is this the expected behavior?  Is this how SCSS works?  Or is this something unique to Python SCSS?  Would it be difficult to add this feature?  It seems like it would be extremely useful.

**Comment by klen** [comment]
Use https://github.com/Kronuz/pyScss man. This project is closed. Sorry.
