### ISSUE TITLE
Add "watch" functionality, similar to Ruby's sass tool

### ISSUE THREAD

**Issue by singingwolfboy** [klen/python-scss#4]
The "sass" tool installed with Ruby's haml gem has an awesome feature where you can watch a file or a directory, and whenever any of those .scss files are changed, the .css files are instantly and automatically recompiled from the newly changed .scss file. Would it be possible to add this feature to python-scss?

**Comment by singingwolfboy** [comment]
As a stopgap, you can run the scss automatically every few seconds using GNU watch, from here: http://procps.sourceforge.net/

It's not as good as only running the tool when the file actually changes (uses more system resources), but it gets the job done anyway.

**Comment by klen** [comment]
I added a simple implementation of `watch` in version 0.6.5, Should work with files and directories.

**Comment by klen** [comment]
Use -w, --watch option.

**Comment by singingwolfboy** [comment]
In that case, it should be documented in the `scss` help message. I didn't know that feature existed!

**Comment by klen** [comment]
I added it just now :) Version 0.6.5 done 5 minutes ago

**Comment by singingwolfboy** [comment]
Oh wow! Thanks! Updated (and I updated the Macports port, as well)
