### ISSUE TITLE
CSS3 not selector

### ISSUE THREAD

**Issue by jchia** [klen/python-scss#8]
Is SCSS expected to support the not selector in CSS3? The following fails to compile. The error is "invalid literal for int() with base 16: 'au'"

div#autoscroll_container .ui-button-text-only:not(.ui-state-active) .ui-button-text {
    // These two lines cause a blur effect.
    color: transparent;
    text-shadow: 0px 0px 4px #111111;
}

No such problem exists for the sass command from rubygems; the translation succeeded with:

div#autoscroll_container .ui-button-text-only:not(.ui-state-active) .ui-button-text
  // These two lines cause a blur effect.
  color: transparent
  text-shadow: 0px 0px 4px #111111

**Comment by klen** [comment]
To be fixed on next week. Thanks.

**Comment by klen** [comment]
Fixed in version 0.8.2
