### ISSUE TITLE
bug in parsing

### ISSUE THREAD

**Issue by lgriesterer** [klen/python-scss#9]
This scss script is not parsed:

.bug {
    background: -moz-linear-gradient (top, #DDD, #AAA);
}

**Comment by lgriesterer** [comment]
Fixed by this patch (which pass all the script in tests/):

<pre>
  27c27
  &lt; FUNCTION = Regex(r"-?[a-zA-Z_][-a-zA-Z0-9_]*") + PARAMS
  ---
  &gt; FUNCTION = Regex(r"[a-zA-Z_][-a-zA-Z0-9_]*") + PARAMS
</pre>

**Comment by klen** [comment]
Fixed in version 0.8.22

Thanks
